### ISSUE TITLE
Changing the key binding

### ISSUE THREAD

**Issue by fniessen** [abo-abo/ace-link#12]
I just found out about your package. Seems I'll not stop using it from now on... Thanks for it.

However, I'd like to change the binding from "o" to "f" (for example, as it reminds me bindings in Firefox, from an extension to do just that, and as well, and what I choose for `w3m-lnum`). Can you foresee a defcustom therefore?

**Comment by abo-abo** [comment]
You don't have to use `ace-link-setup-default`. I put it there as a template to that people not experienced with Elisp can get a default binding, and also so that they see how to customize it.
Just copy paste the code into your config, changing `"o"` to `"f"`:

```elisp
(require 'ace-link)
(eval-after-load "info"
  '(define-key Info-mode-map "f" 'ace-link-info))
(eval-after-load "help-mode"
  '(define-key help-mode-map "f" 'ace-link-help))
(eval-after-load "eww"
  '(progn
    (define-key eww-link-keymap "f" 'ace-link-eww)
    (define-key eww-mode-map "f" 'ace-link-eww)))
```

**Comment by fniessen** [comment]
Ok, we can define all the links by ourselves, but I'd find it much more practical to be able to define once the key binding, and just call your function.  It'd help the DRY principle.

Moreover, would you add new modes in which ace-link would work, we'd simply inherit it when updating your package. Not if we copy/paste the above code in our .Emacs file.

**Comment by abo-abo** [comment]
Fine, have it your way:)

**Comment by fniessen** [comment]
Thanks for your quick (and desired) patch!

**Comment by fniessen** [comment]
I get the following error:

    Symbol's value as variable is void: ace-link-help

**Comment by abo-abo** [comment]
Just update to latest avy and restart Emacs.
