### ISSUE TITLE
Use sequential letters

### ISSUE THREAD

**Issue by fniessen** [abo-abo/ace-link#13]
On your demo, we see all letters being sequential (a, b, c, d, etc.).

In my case, when C-h f'ing ace-link-setup-default, and calling ace-link, I have two links, respectively bound to "a" and "s"!?  See http://screencast.com/t/nLBDUqtO6.

Could you make it always sequential?  Or is there a reason here to have "a" and "s"?

**Comment by abo-abo** [comment]
You can customize `avy-keys`. By default, they are `asdfghjk` (home row).

**Comment by fniessen** [comment]
OK, thanks!
