### ISSUE TITLE
ace-link-org: call-interactively: Symbol's value as variable is void: ace-link-org

### ISSUE THREAD

**Issue by wiedzmin** [abo-abo/ace-link#18]
subj: it seems there is apostrophe needed before ace-link-org at L130

**Comment by abo-abo** [comment]
Works fine for me:

    (call-interactively 'ace-link-org)

The line 130 is fine as well, since `avy--with-avy-keys` is a macro and not a function.

**Comment by wiedzmin** [comment]
Hmm, it's a bit strange, cause I was able to reproduce it just recently, with the message above. Will close it for now, maybe it will pop up later.
