### ISSUE TITLE
Error in Gnus: call-interactively: Wrong type argument: number-or-marker-p, "zero candidates"

### ISSUE THREAD

**Issue by Jehops** [abo-abo/ace-link#20]
In either a gnus-summary-mode buffer or a gnus-article-mode buffer calling ace-link-gnus gives the error in the subject.  If the function is called from summary buffer, the point jumps to first link (but the link isn't opened), if it's called a second time the point jumps to the second link and so on.

**Comment by abo-abo** [comment]
Works fine on Emacs 24.5. What's your Emacs version?

**Comment by Jehops** [comment]
24.5.1

I'm using this with mostly with Gmane/Gwene.  For example, with articles for RSS feeds (e.g. nntp+news.gmane.org:gwene.org.emacsen.planet) that always have a link to the original page.

**Comment by abo-abo** [comment]
Thanks I could reproduce with planetemacsen (I couldn't with regular email). Please test.

**Comment by Jehops** [comment]
Oleh Krehel <notifications@github.com> writes:

> Thanks I could reproduce with planetemacsen (I couldn't with regular
> email). Please test.

That seems to have fixed it.  Thank you.
