### ISSUE TITLE
highlighting bug with ace-link-addr

### ISSUE THREAD

**Issue by blaenk** [abo-abo/ace-link#24]
The command seems to work fine, it's just that the first letter of the url gets its highlighting messed up, as if it's taking on the font face of the preceding or surrounding font-face.

comments:

![bug2](http://i.imgur.com/O6UQ6w2.png)

strings:

![bug](http://i.imgur.com/VvWhnXT.png)

**Comment by abo-abo** [comment]
Thanks.
