### ISSUE TITLE
First link in ace-link-eww may not be considered

### ISSUE THREAD

**Issue by fice-t** [abo-abo/ace-link#25]
If the the first link in any mode that uses `ace-link--eww-collect` starts at `(window-start)`, then it is skipped.

**Comment by abo-abo** [comment]
Can't reproduce in org-mode. Please give a concrete example.

**Comment by fice-t** [comment]
Org looks like it uses a different function. Try:
`M-x eww RET gnu.org`.

And then `o` will not include the first link.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by fice-t** [comment]
It works, thanks.
