### ISSUE TITLE
ace-link with avy-style

### ISSUE THREAD

**Issue by fice-t** [abo-abo/ace-link#27]
Hi, I use the default avy-style `at-full`, but ace-link seems to use `pre`. Can there be a way to easily customize this?

Thanks.

**Comment by fice-t** [comment]
@abo-abo The functions use a style function directly like `avy--overlay-post` instead of `(avy--style-fn avy-style)`. Was this intentional?

I noticed that `at-full` doesn't seem to work well with proportional fonts, so I can see why `post` would be forced in `ace-link-eww`, but outside of that it either does nothing (in Org and Custom) or seems fine.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by fice-t** [comment]
Thanks, that works.
