### ISSUE TITLE
Visual regression in ace-link-info?

### ISSUE THREAD

**Issue by fice-t** [abo-abo/ace-link#30]
I noticed that in your gif showcasing ace-link-info, the character overlays are placed in the space right after `*`.

With the latest version of ace-link this does not happen, and all of the links are shifted over one (which is what I'd expect if I'd never seen the gif).

Is there a way to get the behaviour shown in the gif? It looks slightly nicer.

**Comment by abo-abo** [comment]
Looks the same to me. Look at your `avy-styles-alist`, try to customize it.

**Comment by fice-t** [comment]
I've tried `M-x ace-link-info` in `emacs -Q` with a nil `avy-styles-alist` with `avy-styles` `pre, post, at, at-full`.

Is there something I'm missing? Even `pre` puts the overlay after the space, not on it.

**Comment by abo-abo** [comment]
> Even pre puts the overlay after the space, not on it.

What does this look like? Can you give a screenshot?

**Comment by fice-t** [comment]
![ace-link](https://cloud.githubusercontent.com/assets/13156601/18420696/f13a732a-7835-11e6-9bc4-98f7a102ce63.png)

**Comment by abo-abo** [comment]
Now I see what you mean. You can solve this with:

```elisp
(setq avy-keys-alist
      `((ace-link-info
         ,@(number-sequence ?a ?z))))
```

Of course, the fix applies to situations with less than 27 links in the window.

**Comment by fice-t** [comment]
Thanks, that's certainly helpful for `ace-link-info`, but the overlays, while usually only a single char wide, still appear after the space and not on it.

Is the screencast using `ace-jump-mode`? I guess that could explain it. Is there an easy way to detect that the current buffer is a directory node and move the overlays back one character only in that case? If not then there's no use worrying about it.
