### ISSUE TITLE
URL:s opened automatically?

### ISSUE THREAD

**Issue by joncol** [abo-abo/ace-link#32]
When running ace-link on an info page containing http links, all of the links are automatically opened before having pressed the key for a specific link. Is this the intended behavior?

**Comment by abo-abo** [comment]
It's likely that there was only a single link on the page. In that case, it opens automatically.

**Comment by joncol** [comment]
There were actually two links. When looking at the info page for Haskell mode/Introduction, both links open up automatically.

**Comment by joncol** [comment]
Also, when running ace-link on the "An introduction to Programming in Lisp" info page, both links are opened automatically and focus is switched to the browser window.
