### ISSUE TITLE
Docker error?!

### ISSUE THREAD

**Issue by azoreseuropa** [abo-abo/ace-link#54]
I am using Docker and ace-link. Error: Your input can't be opened
VLC is unable to open the MRL 'http://127.0.0.1:6878/ace/getstream?id='. Check the log for details.

It was working fine. Mine is the latest version of Mojave and MacBook Pro Mid 2014

**Comment by abo-abo** [comment]
Please provide more info. It's not clear about the `major-mode` and the link.

**Comment by azoreseuropa** [comment]
> Please provide more info. It's not clear about the `major-mode` and the link.

Never mind. It have been resolved. I just found out that ace stream list site was the issue. Sorry about that. You can closed it now. Thanks!

**Comment by abo-abo** [comment]
OK, thanks.
