### ISSUE TITLE
Unable to install from melpa-stable

### ISSUE THREAD

**Issue by glucas** [abo-abo/ace-link#6]
Just tried to install ace-link 0.2.0 from melpa-stable from Emacs 24.4. I'm getting a dependency error:

     package-compute-transaction: Package `noflet-0.0.10' is unavailable

I found noflet on github so I can work around this, but seemed worth bringing to your attention.

**Comment by abo-abo** [comment]
Thanks for reporting. It seems that `noflet` doesn't yet have a release.
I'll have to ask @nicferrier.

**Comment by nicferrier** [comment]
Why would I put this in melpa? melpa sucks.

**Comment by abo-abo** [comment]
> Why would I put this in melpa? melpa sucks.

Are you being sarcastic, Nic? I can't tell.

**Comment by nicferrier** [comment]
No. Grumpy but not sarcastic.

**Comment by abo-abo** [comment]
Then just push one tag. Everything else is automatic.

**Comment by nicferrier** [comment]
But that would mean I supported melpa.

**Comment by abo-abo** [comment]
If you don't want to do it, it's fine. I can post a fork on MELPA.
Your current HEAD is still broken, by the way.

**Comment by nicferrier** [comment]
of noflet?

**Comment by abo-abo** [comment]
obviously

**Comment by abo-abo** [comment]
@glucas it should work now, no noflet - no problem.

**Comment by glucas** [comment]
Yup, works great. Thanks!
