### ISSUE TITLE
eshell support

### ISSUE THREAD

**Issue by divansantana** [abo-abo/ace-link#69]
Hi,

Seems ace-link-org appears to work in eshell. But ace-link by default doesn't work.

Should be a quick fix?

**Comment by divansantana** [comment]
Same goes for telega.el . ace-link-org there too works, but not ace-link.

**Comment by abo-abo** [comment]
Thanks. Added `eshell-mode`. What's the mode for `telega.el`?

**Comment by divansantana** [comment]
@abo-abo `telega-chat-mode` thanks.

**Comment by abo-abo** [comment]
Thanks.
