### ISSUE TITLE
Feature request: support message mode

### ISSUE THREAD

**Issue by WorldsEndless** [abo-abo/ace-link#7]
I noticed that org mode is added, which is great. Gnus users may most often encounter links in Message-mode buffers, which may have to be tabbed through. It would be great if this was supported.

**Comment by abo-abo** [comment]
This should already be possible with `ace-link-eww`. Just `(require 'eww)` beforehand.

**Comment by WorldsEndless** [comment]
Perhaps I misunderstand. When I receive a message I see links like "view it on GitHub" but ace link doesn't see anything. Screenshot attached. 
![acelink](https://cloud.githubusercontent.com/assets/5042778/6714024/78930baa-cd6c-11e4-8f2b-6c977d776aba.jpg)

**Comment by abo-abo** [comment]
`ace-link-eww` is working fine for me:
![ace-link-eww](https://cloud.githubusercontent.com/assets/2937359/6714714/14748fe4-cd9a-11e4-859f-203ab74503ec.png)

What's your Emacs version?

**Comment by WorldsEndless** [comment]
I restarted but still no love. GNU Emacs 25.0.50.6 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.9) of 2015-02-10 on localhost.localdomain

**Comment by WorldsEndless** [comment]
I thought it might have to do with my gnus html setting, so I tried each of the following: 

    ;(setq mm-text-html-renderer 'gnus-w3m)
    ;(setq mm-text-html-renderer ())
    (setq mm-text-html-renderer 'shr)
    ;(setq mm-text-html-renderer 'html2text)

Still no luck, though. I've had one email that it mostly worked in--one that was formatted purely as HTML. But even then some of the links didn't show up.

**Comment by abo-abo** [comment]
I only need a way to collect the point positions candidates in the current window
bounds in order for `ace-link` to work for any mode.

If you're familiar with Elisp, you could try to debug `ali--eww-collect-references`
to see at which point it's failing to collect the necessary candidates.

Otherwise, just tell me how you currently cycle between links, i.e.  which function is bound to
<kbd>TAB</kbd> takes you from one link to the next one.

**Comment by WorldsEndless** [comment]
Looks like it's just calling `widget-forward`

**Comment by abo-abo** [comment]
OK, that really needed a new candidate collecting scheme.
Let me know if it works.

**Comment by WorldsEndless** [comment]
Works perfectly. Thanks!

**Comment by WorldsEndless** [comment]
Gnus often acts from the summary buffer, performing upon the article buffer; it does this with gnus-summary-widget-forward (when in summary mode). It will be really useful if ace-link can work from either the summary buffer or the article/message buffer in gnus. Otherwise the user will always have to press TAB before launching ace-link.

**Comment by abo-abo** [comment]
Should be fixed if I understood you correctly.
