### ISSUE TITLE
`ace-link-org` errors out before Org is loaded

### ISSUE THREAD

**Issue by duckwork** [abo-abo/ace-link#79]
I tracked it down to the fact that `org-element-lineage` isn't auto-loaded from org-element.el.  I've added an `autoload` declaration to my own config, but I haven't opened a PR here because I'm not sure where it should go or if or how it should be tested.

FYI:
- Emacs version: 28.0.50
- Org version: 9.4.6
- Ace-link commit: e1b1c91

**Comment by duckwork** [comment]
Hey @wowhxj , I added `(autoload 'org-element-lineage "org-element")` before the call to `(ace-link-setup-default)` in my config, but I actually don't use ace-link any more.

I've since switched to [link-hint](https://github.com/noctuid/link-hint.el), which I found to be better for my use. 

Hope this helps tho!

**Comment by wowhxj** [comment]
> Hey @wowhxj , I added `(autoload 'org-element-lineage "org-element")` before the call to `(ace-link-setup-default)` in my config, but I actually don't use ace-link any more.
> 
> I've since switched to [link-hint](https://github.com/noctuid/link-hint.el), which I found to be better for my use.
> 
> Hope this helps tho!

I fixed it and thanks very much bro. On the mean time, I'll try this package.
