### ISSUE TITLE
Support for jumping to buttons

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/ace-link#8]
It would be useful to jump to a particular button in a buffer, like in `helm-mode`.

**Comment by abo-abo** [comment]
Since when does `helm-mode` have buttons?

**Comment by tuhdo** [comment]
Sorry, it was `help-mode` that usually contains buttons in it.

**Comment by abo-abo** [comment]
I see. Can you provide an example buffer for which `ace-link-help` doesn't work?

**Comment by tuhdo** [comment]
Sorry again. It should be `custom-mode` that should be frequently used after opening a variable in `help-mode`. For example:

- <kbd>C-h v</kbd> and type `company-backends`.
- Click `Customize`.
- Lots of buttons here.

It would be useful to jumps to a button (or any widget there) quickly.
